# This source file is subject to the (Open Source Initiative) BSD license
# that is bundled with this package in the LICENSE file. It is also available
# through the world-wide-web at this URL: http://www.ontic.com.au/license.html
# If you did not receive a copy of the license and are unable to obtain it through
# the world-wide-web, please send an email to license@ontic.com.au immediately.
# Copyright (c) 2010-2016 Ontic. (http://www.ontic.com.au). All rights reserved.

---

- name: 'Exim | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - 'exim'
    - 'exim-package'
    - 'exim-configure'
    - 'exim-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Exim | Define Exim service name.'
  set_fact:
    exim_service_name: '{{ exim_default_service_name }}'
  when: '{{ not exim_service_name }}'
  tags:
    - 'exim'
    - 'exim-package'
    - 'exim-configure'
    - 'exim-service'
    - 'package'
    - 'configure'
    - 'service'

- name: 'Exim | Define Exim packages.'
  set_fact:
    exim_packages: '{{ exim_default_packages }}'
  when: '{{ not exim_packages }}'
  tags:
    - 'exim'
    - 'exim-package'
    - 'exim-configure'
    - 'exim-service'
    - 'package'
    - 'configure'
    - 'service'

- include: 'package.yml'
  tags:
    - 'exim'
    - 'exim-package'
    - 'package'

- include: 'configure.yml'
  tags:
    - 'exim'
    - 'exim-configure'
    - 'configure'

- include: 'service.yml'
  tags:
    - 'exim'
    - 'exim-service'
    - 'service'